version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GPT4ALL_MODEL_PATH=${GPT4ALL_MODEL_PATH}
    volumes:
      - ./backend:/app
      - ./models:/models
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  gui:
    build: 
      context: ./gui
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./gui:/app
    depends_on:
      - backend
